In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [ ]:
print(a + 5 )                          # Add 5 to each element
print(b * 2 )                          # Multiply each element by 2
print(a.sum())                         # Sum of all elements
print(b.mean())                        # Mean of all elements

[6 7 8]
[[2 4]
 [6 8]]
6
2.5


In [ ]:
print(np.zeros((2, 3)))             # 2x3 array of zeros
print(np.ones((3, 2)))              # 3x2 array of ones
print(np.arange(0, 10, 2))          # Array: [0, 2, 4, 6, 8]
print(np.linspace(0, 1, 5))         # 5 numbers from 0 to 1

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [5]:
print(a[0])                         # First element
print(b[:, 1])                      # Second column
print(a[1:])                        # Slice from index 1 to end

1
[2 4]
[2 3]


In [8]:
print(np.arange(6).reshape((2, 3)))    # 2x3 array

[[0 1 2]
 [3 4 5]]


In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print(np.dot(m1, m2))                # Matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
np.random.rand(2, 2)         # 2x2 array of random numbers

array([[0.36267006, 0.06816811],
       [0.21967658, 0.69194787]])

In [14]:
np.save('my_array.npy', a)
np.load('my_array.npy')

array([1, 2, 3])